/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    OTPForm: typeof import('./src/components/OTPForm.vue')['default']
    OTPInput: typeof import('./src/components/OTPInput.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    TableView: typeof import('./src/components/TableView.vue')['default']
  }
}
